### ISSUE TITLE
edit profile

### ISSUE THREAD

**Issue by SpencerCornelia** [danlyg/ProjectVagabond#23]
I clicked edit profile from the user profile page and it led me to the form correctly.

However, when I wanted to click submit button to edit my changes, the page would not scroll down far enough to allow me to see the button.  I was only able to see the input fields with password confirmation as the bottom most field on the page.

**Comment by ccslakey** [comment]
Hey spencer, some of our forms aren't bootstrappy/responsive yet so you may have to zoom out to view some of the forms for now. We'll take care of it, thanks!

**Comment by ccslakey** [comment]
Fixed! I'll close this issue now
